### ISSUE TITLE
尝试将pxder封装成docker后，出现问题

### ISSUE THREAD

**Issue by Luobogao** [Tsuk1ko/pxder#20]
使用docker的node:latest镜像创建容器并且在容器内登入pixiv并完成好各种设定之后，
在容器内的bash运行pxder来下载图片是没有问题的。

但是，

我尝试编写了以下的`docker-compose.yml`
```
version: "2"
services:
  pxder:
    image: luobogao/pxder:private
    container_name: pxder
    volumes:
      - ./images:/images
    command:
      - bash start.sh
```

将pxder相关的命令写入start.sh，内容是
```
pxder -f && pxder -F && pxder -b && pxder -B
```

然后 `docker-compose up` 运行容器之后，出现以下报错并退出
```
[root@myrrh pxder]# docker-compose up
Recreating pxder ... done
Attaching to pxder
pxder    | internal/modules/cjs/loader.js:775
pxder    |     throw err;
pxder    |     ^
pxder    | 
pxder    | Error: Cannot find module '/bash /start.sh'
pxder    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
pxder    |     at Function.Module._load (internal/modules/cjs/loader.js:677:27)
pxder    |     at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
pxder    |     at internal/main/run_main_module.js:17:11 {
pxder    |   code: 'MODULE_NOT_FOUND',
pxder    |   requireStack: []
pxder    | }
pxder exited with code 1
```

我想请问一下这是node的锅还是docker的锅（（（（
如果这是node的锅的话，应该如何处理？

我对node不是很熟悉，还麻烦大佬帮忙瞧一下pwp

**Comment by Tsuk1ko** [comment]
@Luobogao 我对 docker 也不是很了解，这个 start.sh 是哪来的

**Comment by Luobogao** [comment]
emmmmmm不好意思，刚才有点混乱（
刚才尝试了把pxder的命令写进start.sh，内容是
```
pxder -f && pxder -F && pxder -b && pxder -B
```
这样子来运行pxder，使用`docker-compose up`出现问题。

**Comment by Tsuk1ko** [comment]
@Luobogao 所以是用了什么命令来启动这个脚本的，这是 node 的报错找不到 /bash /start.sh 模块，我无法想象这是怎么跟 node 扯上关系的

**Comment by Luobogao** [comment]
查阅了一下资料，
后来把`docker-compose.yml`更改成
```
version: "2"
services:
  pxder:
    image: luobogao/pxder:private
    container_name: pxder
    volumes:
      - ./images:/images
    command: bash -c "start.sh"
```
然后就好了（（（（（（（（（（（（

大晚上还来打扰您真是不好意思
